version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api: 
    container_name: node-container
    build: .
    restart: always
    image: node-com-tdd
    command: npm run debug
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist:/usr/src/node-com-tdd/dist
      - ./node_modules:/usr/src/node-com-tdd/node_modules
      - ./package.json:/usr/src/node-com-tdd/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo